### ISSUE TITLE
Can't find your blog?

### ISSUE THREAD

**Issue by gemmadlou** [giapnguyen74/nqlx#1]
You mention it in the read me but no links. Is it this:

https://codeburst.io/i-hate-redux-so-i-write-my-own-state-management-in-the-weekend-7a7b159c81c7

**Comment by giapnguyen74** [comment]
Yes it is, I hope release first version in the week and update full document. But still work on state persistent and server side distribution. I also optimize code after compare with mobx, the version is slower than 20%; although I think in features, gstate should compare with mobx-state-tree not mobx. Ongoing version nearly as fast as mobx. So stay tune.

**Comment by gemmadlou** [comment]
Could the link be added to the readme? For reference? I saw the link on twitter and that's the only way I was able to find the link again. I like your perspective and I think the article makes a good read.

**Comment by giapnguyen74** [comment]
I've completed first version + full document.
